source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.4'

gem 'bundler'

# Json gem
gem 'json', '1.8.3'
# HTTP server
gem 'unicorn', '4.9.0'
# Use postgresql as the database for Active Record
gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution
  gem 'byebug'
  gem 'rspec-core', '3.3.2'
  gem 'simplecov', require: false
  gem 'rspec-rails', '3.3.3'
  gem 'rspec-support', '3.3.0'
  gem 'database_cleaner', '1.5.1'
end

gem 'yaml_db', '0.3.0'

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your
  # application running in the background.
  # Read more: https://github.com/rails/spring
  gem 'spring'
end

# Load environment variables from a .env file
gem 'dotenv-rails', '2.0.2'

group :production do
  gem 'i18n', '0.7.0'
end

gem 'sidekiq', '4.0.1'
gem 'predictionio', '0.9.6'

# Development environment specific libraries
group :development do
  gem 'pry'

  gem 'rubocop', '0.35.0', require: false

  # Sinatra gem to view Sidekiq progress
  gem 'sinatra', '1.4.6'

  # Capistrano deployment specific files and settings
  gem 'capistrano', '3.4.0'
  gem 'capistrano-ext', '1.2.1'
  gem 'capistrano-rvm', '0.1.2'
  gem 'capistrano-rails', '1.1.5', require: false
  gem 'capistrano-unicorn-nginx', '3.4.0', require: false
  gem 'capistrano-touch-linked-files', '0.3.0', require: false
  gem 'capistrano-sidekiq', '0.5.3', require: false
  gem 'capistrano-bundler', '1.1.4'
end

# Redis driver
gem 'redis', '3.2.1'

# For API versioning
gem 'versionist'

# Plist parsing
gem 'plist'

gem 'bcrypt-ruby', '3.1.5', require: 'bcrypt'

# AWS sdk for storing files
gem 'aws-sdk', '2.2.1'
gem 'fog', '1.36.0'
gem 'fog-aws', '0.7.6'
gem 'carrierwave', '0.10.0', git: 'https://github.com/carrierwaveuploader/carrierwave'
gem 'connection_pool', '2.2.0'

# RSS/Atom feed reader
gem 'feedjira', '2.0.0'

# URL shortener gem
gem 'shortener', '0.5.5'

# Metrics collection
gem 'riemann-metrics'
